eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083
spring:
  application:
    name: school-service
  cloud:
    config:
      enabled: false
  config:
   import: optional:config.server:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: Seth16
  jpa:
   hibernate:
    ddl-auto: update
    database-platform: MySQL


