eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082

spring:
  application:
    name: student-service

  cloud:
    config:
      enabled: false  # Ensure that Spring Cloud Config is disabled if not used

  config:
    import: optional:configserver:http://localhost:8888  # This is the correct format according to the error message

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: Seth16

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: MySQL
